"use client";
import Image from "next/image";
import Link from "next/link";
import { Suspense, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { createUserWithEmailAndPassword, signInWithEmailAndPassword, signInWithPopup, updateProfile, sendEmailVerification, signOut } from "firebase/auth";
import { firebaseAuth, googleProvider } from "@/lib/firebase-client";

function LoginContent(){
 const [mode,setMode]=useState<"login"|"signup">("login"); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [name,setName]=useState(""); const [phone,setPhone]=useState(""); const [company,setCompany]=useState(""); const [error,setError]=useState(""); const [busy,setBusy]=useState(false); const router=useRouter(); const params=useSearchParams();
 async function exchange(profile?:{name?:string;phone?:string;company?:string}){ const user=firebaseAuth.currentUser; if(!user) throw new Error("Authentication did not complete."); const token=await user.getIdToken(true); const r=await fetch("/api/auth/session",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({idToken:token,profile})}); const j=await r.json(); if(!r.ok) throw new Error(j.error?.message||"Unable to create secure session."); router.push(j.redirect||"/client"); router.refresh(); }
 async function submit(e:React.FormEvent){ e.preventDefault(); setBusy(true); setError(""); try { if(mode==="signup"){ if(!name.trim()) throw new Error("Name is required."); const cred=await createUserWithEmailAndPassword(firebaseAuth,email,password); await updateProfile(cred.user,{displayName:name.trim()}); await sendEmailVerification(cred.user); await signOut(firebaseAuth); setMode("login"); setPassword(""); setError("Account created. Please verify your email from the Firebase verification email, then sign in."); } else { const cred=await signInWithEmailAndPassword(firebaseAuth,email,password); if(!cred.user.emailVerified){ await signOut(firebaseAuth); throw new Error("Please verify your email address first. Check your inbox for the Firebase verification email."); } await exchange(); } } catch(err:any){ setError(err?.code?.replace("auth/","")?.replaceAll("-"," ") || err?.message || "Authentication failed."); } finally { setBusy(false); } }
 async function google(){ setBusy(true); setError(""); try { await signInWithPopup(firebaseAuth,googleProvider); await exchange(); } catch(err:any){ setError(err?.code?.replace("auth/","")?.replaceAll("-"," ") || err?.message || "Google sign-in failed."); } finally { setBusy(false); } }
 return <main className="login-shell"><div className="login-box"><Image className="login-logo" src="/coder-world-logo.jpeg" alt="CODER WORLD" width={100} height={100}/><div style={{display:"flex",gap:8,marginBottom:20}}><button type="button" className={mode==='login'?"btn btn-primary":"btn"} onClick={()=>{setMode("login");setError("")}}>Sign in</button><button type="button" className={mode==='signup'?"btn btn-primary":"btn"} onClick={()=>{setMode("signup");setError("")}}>Create account</button></div><h1 style={{fontFamily:"'Space Grotesk',sans-serif",textAlign:"center"}}>{mode==='login'?"Secure Login":"Client Signup"}</h1><p className="muted" style={{textAlign:"center"}}>{mode==='login'?"Admin and authorized client access.":"Create your secure CODER WORLD client account."}</p>{mode==='signup'&&<><div className="form-grid"><div className="field"><label>Name</label><input value={name} onChange={e=>setName(e.target.value)} required/></div><div className="field"><label>Phone</label><input value={phone} onChange={e=>setPhone(e.target.value)}/></div></div><div className="field" style={{marginTop:16}}><label>Company</label><input value={company} onChange={e=>setCompany(e.target.value)}/></div></>}<form className="form" onSubmit={submit} style={{marginTop:16}}><div className="field"><label>Email</label><input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></div><div className="field"><label>Password</label><input type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={8} required/></div><button className="btn btn-primary" disabled={busy}>{busy?(mode==='login'?"Signing in...":"Creating account..."):(mode==='login'?"Sign in →":"Create client account →")}</button>{(error||params.get("error"))&&<div className="toast">{error||params.get("error")}</div>}</form><div style={{display:"grid",gridTemplateColumns:"1fr auto 1fr",gap:10,alignItems:"center",margin:"20px 0",color:"#718099"}}><span style={{height:1,background:"rgba(110,150,220,.16)"}}></span><small>OR</small><span style={{height:1,background:"rgba(110,150,220,.16)"}}></span></div><button type="button" className="btn" onClick={google} disabled={busy} style={{width:"100%",justifyContent:"center"}}>Continue with Google</button><p className="muted" style={{fontSize:12,textAlign:"center",marginTop:18}}>Google users can complete phone/company details later from their client profile.</p><p className="muted" style={{fontSize:12,textAlign:"center"}}>← <Link href="/">Back to CODER WORLD</Link></p></div></main>
}

export default function Login(){
 return <Suspense fallback={<main className="login-shell" aria-busy="true"/>}><LoginContent/></Suspense>;
}
